apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-platform
  labels:
    app.kubernetes.io/name: devops-platform
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.frontend }}
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.services.frontend.port }}
          - path: {{ .Values.ingress.paths.api }}
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: {{ .Values.services.gateway.port }}
