{{- $swaggerUi := index .Values.services "swagger-ui" }}
{{- if and $swaggerUi $swaggerUi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openapi-spec
  labels:
    app.kubernetes.io/name: swagger-ui
data:
  openapi.yaml: |
{{ .Files.Get "files/openapi.yaml" | nindent 4 }}
{{- end }}
