apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-platform.postgresSecretName" . }}
  labels:
    app.kubernetes.io/name: postgres
type: Opaque
stringData:
  password: {{ include "devops-platform.postgresPassword" . | quote }}
