{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ $svc.port }}
      targetPort: http
    {{- with $svc.metricsPort }}
    - protocol: TCP
      name: metrics
      port: {{ . }}
      targetPort: metrics
    {{- end }}
---
{{- end }}
{{- end }}
