global:
  image:
    registry: ghcr.io/aet-devops26/team-panic-at-the-console
    tag: main
  namespace: default

services:
  frontend:
    enabled: true
    port: 3000
    image:
      repository: frontend

  gateway:
    enabled: true
    port: 8080
    image:
      repository: gateway
    env:
      - name: NATS_URL
        value: nats://nats:4222

  incident-service:
    enabled: true
    port: 8081
    image:
      repository: incident-service
    env:
      - name: DATABASE_URL
        value: "postgres://devops:devops@postgres:5432/incidents"
      - name: NATS_URL
        value: nats://nats:4222

  event-service:
    enabled: true
    port: 8082
    image:
      repository: event-service
    env:
      - name: DATABASE_URL
        value: "postgres://devops:devops@postgres:5432/events"
      - name: NATS_URL
        value: nats://nats:4222

  rule-engine:
    enabled: true
    port: 8083
    image:
      repository: rule-engine
    env:
      - name: DATABASE_URL
        value: "postgres://devops:devops@postgres:5432/rules"
      - name: NATS_URL
        value: nats://nats:4222

  user-service:
    enabled: true
    port: 8084
    image:
      repository: user-service
    env:
      - name: DATABASE_URL
        value: "postgres://devops:devops@postgres:5432/users"

  notification-service:
    enabled: true
    port: 8085
    image:
      repository: notification-service
    env:
      - name: DATABASE_URL
        value: "postgres://devops:devops@postgres:5432/notifications"
      - name: NATS_URL
        value: nats://nats:4222

  webhook-service:
    enabled: true
    port: 8086
    image:
      repository: webhook-service
    env:
      - name: NATS_URL
        value: nats://nats:4222

  genai-service:
    enabled: true
    port: 8087
    image:
      repository: genai-service
    env:
      - name: NATS_URL
        value: nats://nats:4222
