kube-prometheus-stack:
  grafana:
    adminPassword: ENC[AES256_GCM,data:DCsGqZ0qJ9WfOPeAkd6PXuNuUkd2,iv:EIp2H7BTap/nr3DtEcmaDta7NfvqxLNkQmWXIPa9IQ8=,tag:DSekcr8Sm9UPpr2VmHqbxQ==,type:str]
sops:
  age:
    - recipient: age16sgwfcnyzjlfkpn3wmpd9zndtcjfq39vhlazearvstsjzl6tw3fq7kcjnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMDVRTWlCUjgrWU90RGpk
        ajY2d1NTY2ZmVXVwQk9SS1p0Y2tWeExLUEEwClRWVTlGR1AxTTBZYlZrcEw0N1Q1
        dTh2anhDaDlhWXRKTTdDRHRNQTV6YXMKLS0tIElOM21yUU5oME5hNHVXRkJWa2tl
        cjJKblVrTlI4RkZIOW9qd1ZjTVIwR0EKdEJWixEwrfLvDhQ6nz65735XAKmmsqM1
        ZQtnVmVrEkSszQSqEbpq6IQ3byUP8nYdgMKBUTLsgWGwLI5PTl2qNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T14:24:16Z"
  mac: ENC[AES256_GCM,data:9k41PtGs5uLQGlC0IVfzTtH48Fvo0ADUmxP7c5MlzFuxRqMHGVEci86jxzH9RkLHZ53/jeHxM8x18/kiDeptsQMcHL3bVsUL7F8XJ0UXjuXK8P9zFV/YE6Yo1xCCRsKMSpWofcqF1pxoYPIPVTLnJl1p8W5cffwVaQdBHbC/wtA=,iv:83gzrnRqZZ5/F5MguPkKUkE5LAkldUTMHkm9SyHST0U=,tag:Oy6buhgjwNen0vV8NdbIyg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
