kube-prometheus-stack:
  grafana:
    adminPassword: ENC[AES256_GCM,data:AinViRE=,iv:KjXj9gtmmvGEkx3V55ABjpEHq6ZTVZPpHVCe8z/1Ne0=,tag:bmwFmzbh9hcyNERJgwg+pQ==,type:str]
sops:
  age:
    - recipient: age16sgwfcnyzjlfkpn3wmpd9zndtcjfq39vhlazearvstsjzl6tw3fq7kcjnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMDVRTWlCUjgrWU90RGpk
        ajY2d1NTY2ZmVXVwQk9SS1p0Y2tWeExLUEEwClRWVTlGR1AxTTBZYlZrcEw0N1Q1
        dTh2anhDaDlhWXRKTTdDRHRNQTV6YXMKLS0tIElOM21yUU5oME5hNHVXRkJWa2tl
        cjJKblVrTlI4RkZIOW9qd1ZjTVIwR0EKdEJWixEwrfLvDhQ6nz65735XAKmmsqM1
        ZQtnVmVrEkSszQSqEbpq6IQ3byUP8nYdgMKBUTLsgWGwLI5PTl2qNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-08T21:40:24Z"
  mac: ENC[AES256_GCM,data:Gb5rZuvS9I9LUgrsgrzM+AWUMZlOuAmWu4moq1nrFKxxdd5MiZ9+hdun6c4kjl/l5//cJAYKkNQZdKvLCmyvXIsQZq7DSlgbjp4USe49EA6mkZ5Wa9spEl1q3n6E197KBT33oLTzwGR8jGVymrXcKuQu6D4pCebf3LWG26mBSUU=,iv:OpJNaLYH1ZUlej/7f52u+783a5NTzZsuVGtQku5W2PU=,tag:rm81ERxcCTz4U5abAEB3jg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
