global:
  image:
    tag: ENC[AES256_GCM,data:5ZCfUg==,iv:q9La5olJnKgeP7qYOY1MSi1PWRrE/m8VQN3XtCD6Ekc=,tag:u3vJw2v9epLeuhoN0AosHw==,type:str]
secrets:
  postgresPassword: ENC[AES256_GCM,data:5IdZl7Fc9FP4VdzA5JdXJA==,iv:Ko4R0lL7HfZKosGtiO9ooB/CfwHy7bSjjZLvJEYTzqo=,tag:egAMfGR5HK9bq4/e1pq3sg==,type:str]
  logosApiKey: ENC[AES256_GCM,data:ZZabyZkwPDdwQtwJ4zq4ksZeSMaMiAOriVNoIDAVhQ3VRGdavl0U//Mn8QhvfxGMPUszoQ1PYn7c/LHfIdgUP+pN7yfT5uTRZ8gk+v3ddy8gIvzke67+0/re2cv29vdpPY2CyjSTfpPRLHR9LxNqb9KP5/wweMVDcxUKOoSpmOTob4Mps8gGNwcQoxPRs5deTiU+6A==,iv:lH2v3sUiO7AONGWflnUhUm7PjfH47zQotJpvpWzEHu8=,tag:q4t5uph0oQWdJdKI3+jG9w==,type:str]
sops:
  age:
    - recipient: age16sgwfcnyzjlfkpn3wmpd9zndtcjfq39vhlazearvstsjzl6tw3fq7kcjnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXp6WDF4Z1EzUGxocDlP
        eGcweEtrQzZwaEQ1REswSllONG54MVBETXdZCm0zYUdjTEZVUDYzY1RLZWNlMFhk
        cUh5OEhxYk9XWCtKd0lESnQwRzBGcG8KLS0tIERHNGNua0huUVN6WVBPbTZDQzRM
        NTVGbGJ0QVI4UTNicjlzYlNtS1EwZ0kKZak3VUczoUQiVozePVaG6/HAhbPd+bO7
        r54tZV5vVSpaJ1MyjL/r9cRrx5gXdKlOHj18HC4VFiLrDXYmxrjmsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T16:25:14Z"
  mac: ENC[AES256_GCM,data:WDlo6Q8rgW2bo536fRwuWYPTw6eLt1GfTR6ZYnoogfXQ1xNjHa7BRNJjrLU/6mrh0RlaTFoofgw7vRbCM41Hr19gt4fMoAnGB0lsBzcFUUADSAySo/f8QgQOFq3Uo261wseVtgyyHy/vpCByYb/T4Mz05/6RcaLJwkaV8vq9QV0=,iv:eHb/tK8UPf3Fj7ihnsPLI62sV4t31g/QbvHSiRVzMaw=,tag:eo79SENaOJZR3oNCnFIUpQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
