global:
  image:
    tag: ENC[AES256_GCM,data:5ZCfUg==,iv:q9La5olJnKgeP7qYOY1MSi1PWRrE/m8VQN3XtCD6Ekc=,tag:u3vJw2v9epLeuhoN0AosHw==,type:str]
secrets:
  grafanaPassword: ENC[AES256_GCM,data:7MfGu4s=,iv:evg6tZ2oXCXf8IaDVOZF5Qf/MaLnpO5zkhX1weLcgcs=,tag:eVNjl9NKhXdlwkQHUHBk6Q==,type:str]
  postgresPassword: ENC[AES256_GCM,data:5IdZl7Fc9FP4VdzA5JdXJA==,iv:Ko4R0lL7HfZKosGtiO9ooB/CfwHy7bSjjZLvJEYTzqo=,tag:egAMfGR5HK9bq4/e1pq3sg==,type:str]
  logosApiKey: ENC[AES256_GCM,data:ZZabyZkwPDdwQtwJ4zq4ksZeSMaMiAOriVNoIDAVhQ3VRGdavl0U//Mn8QhvfxGMPUszoQ1PYn7c/LHfIdgUP+pN7yfT5uTRZ8gk+v3ddy8gIvzke67+0/re2cv29vdpPY2CyjSTfpPRLHR9LxNqb9KP5/wweMVDcxUKOoSpmOTob4Mps8gGNwcQoxPRs5deTiU+6A==,iv:lH2v3sUiO7AONGWflnUhUm7PjfH47zQotJpvpWzEHu8=,tag:q4t5uph0oQWdJdKI3+jG9w==,type:str]
  jwtSecret: ENC[AES256_GCM,data:uy6FIwSJLrOWp2aQFNj+Xdnf3ZA1YwUZFcnbaDOdHbW7qt8aMxQAhMvq5yhxlTfbUUIP/QJ4OEKUDcakzK+j6w==,iv:a6tZsw3lt7IXehQyA+CA1+Q2TNLVo/w6FWIHbtE2MLQ=,tag:q6yhdNdcHH1wfxCeWiw5aw==,type:str]
  inviteCode: ENC[AES256_GCM,data:gTwi611klYcKf0yp,iv:l4SryQDrkPEawLn/1LzrFX9J+ZM7YWmYnWvUOBM8UPg=,tag:dloFV+8o5FTLSSKEC6Jekw==,type:str]
sops:
  age:
    - recipient: age16sgwfcnyzjlfkpn3wmpd9zndtcjfq39vhlazearvstsjzl6tw3fq7kcjnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXp6WDF4Z1EzUGxocDlP
        eGcweEtrQzZwaEQ1REswSllONG54MVBETXdZCm0zYUdjTEZVUDYzY1RLZWNlMFhk
        cUh5OEhxYk9XWCtKd0lESnQwRzBGcG8KLS0tIERHNGNua0huUVN6WVBPbTZDQzRM
        NTVGbGJ0QVI4UTNicjlzYlNtS1EwZ0kKZak3VUczoUQiVozePVaG6/HAhbPd+bO7
        r54tZV5vVSpaJ1MyjL/r9cRrx5gXdKlOHj18HC4VFiLrDXYmxrjmsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-13T01:43:22Z"
  mac: ENC[AES256_GCM,data:gVvzNwjIFdJnmkT1aDkf+KkA6y+FCuMJcRbshOUna+c8vJlcYP/wH9T97TanfAv4ycuj/NijPrbtsoInstFI4XPuxBjL7t2gQBuvD07ghmHNcwx+YTEE9Qp3B3bNcSwmOTW6TWi46ry1S7xEjnaM1/UI4GTsaCJejVhwwrYPlWY=,iv:5moMa9RR5B8g47O1//tURKsN6ucFoL606iiERwzAneg=,tag:/O9uW6QKzKpWjJAEbJIuGg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
