global:
  image:
    tag: ENC[AES256_GCM,data:5ZCfUg==,iv:q9La5olJnKgeP7qYOY1MSi1PWRrE/m8VQN3XtCD6Ekc=,tag:u3vJw2v9epLeuhoN0AosHw==,type:str]
secrets:
  databaseUrl: ENC[AES256_GCM,data:exIZrojNlp6gvJwlBN8pSn4F28fk3TzoqhPoJrTANS7zb5A/uovb5YJIPLY9+6VjkaXhtmCiVax77+y2T5U3xQGU4rcUHXJCBe0=,iv:/CtwcdSjGW8mrucO1od8PbJd2Lfy9V6/egD1J9YdTyM=,tag:QVpuXgvsqPgywGSidZFsrw==,type:str]
  apiToken: ENC[AES256_GCM,data:h2Osutrp/QZ8CHq+nKM=,iv:dDM6XXUsTOAzB6hC7Ijyfcd6HLMzqE2MB6qwXfTXDuM=,tag:hq6zXwmeXYoLeEaqJeb5sw==,type:str]
sops:
  age:
    - recipient: age16sgwfcnyzjlfkpn3wmpd9zndtcjfq39vhlazearvstsjzl6tw3fq7kcjnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXp6WDF4Z1EzUGxocDlP
        eGcweEtrQzZwaEQ1REswSllONG54MVBETXdZCm0zYUdjTEZVUDYzY1RLZWNlMFhk
        cUh5OEhxYk9XWCtKd0lESnQwRzBGcG8KLS0tIERHNGNua0huUVN6WVBPbTZDQzRM
        NTVGbGJ0QVI4UTNicjlzYlNtS1EwZ0kKZak3VUczoUQiVozePVaG6/HAhbPd+bO7
        r54tZV5vVSpaJ1MyjL/r9cRrx5gXdKlOHj18HC4VFiLrDXYmxrjmsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T14:24:16Z"
  mac: ENC[AES256_GCM,data:MeLYXRVCjXWSmpg2b2gtFvUIumroNAmScJjB49TTTxKjoNC4yWnchUtyFpBInWObm+/XnWfkb3iDCZHl+33U6UQl+VbdyjG1EpdhmP2tJNyVgjntWOzldMrSHFx7AWs2HAksFIePcoSiAQGqfsqp7VMYKF0TRkXTGpxoGmpC3hQ=,iv:cXpMtnBiLQNDjsd1cMZmaD25IpT0fGtah0dV3jxC+AM=,tag:YnOQBkZQJR9mH/oJ9BRP1g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
