# Copy this file to values.prod.dec.yaml and replace placeholders.
# Encrypt it to values.prod.enc.yaml using:
# sops --encrypt --in-place infra/helm/secrets/values.prod.dec.yaml

global:
  image:
    tag: v0.1.0

secrets:
  postgresPassword: "replace-me"
