/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/genai/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GenAI service health check */
        get: operations["genaiHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all incidents */
        get: operations["listIncidents"];
        put?: never;
        /** Manually create a new incident */
        post: operations["createIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single incident by ID */
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update incident status or severity */
        patch: operations["updateIncident"];
        trace?: never;
    };
    "/incidents/{incidentId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the event log for an incident */
        get: operations["listIncidentEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments on an incident */
        get: operations["listComments"];
        put?: never;
        /** Add a comment to an incident */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/genai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger summary regeneration for an incident */
        post: operations["regenerateSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/genai/severity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger severity suggestion regeneration for an incident */
        post: operations["regenerateSeverity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/genai/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger solution suggestions regeneration for an incident */
        post: operations["regenerateSolutions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/genai/postmortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger postmortem regeneration for a resolved incident */
        post: operations["regeneratePostmortem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description GenAI service health status including Ollama reachability. */
        GenaiHealthResponse: {
            /** @example ok */
            status: string;
            /** @example true */
            ollamaReachable: boolean;
            /** @example qwen2.5:3b */
            model: string;
        };
        /** @description Confirmation that an AI generation task was accepted for async processing. */
        RegenAccepted: {
            /** @example true */
            accepted: boolean;
            /**
             * @example SUMMARY
             * @enum {string}
             */
            task: "SUMMARY" | "SEVERITY_SUGGESTION" | "SOLUTION_SUGGESTIONS" | "POSTMORTEM";
        };
        /**
         * @description Incident severity. SEV1 is highest impact.
         * @enum {string}
         */
        Severity: "SEV1" | "SEV2" | "SEV3" | "SEV4";
        /** @enum {string} */
        IncidentStatus: "open" | "investigating" | "resolved";
        /** @description An incident as stored by incident-service. */
        Incident: {
            /** Format: uuid */
            id: string;
            /** @example Checkout 5xx spike */
            title: string;
            description?: string | null;
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["Severity"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        /** @description One entry from an incident's append-only Event Log. */
        IncidentEvent: {
            /** Format: date-time */
            timestamp: string;
            /** @example status_changed */
            type: string;
            /** @example status: open -> investigating */
            description: string;
        };
        /**
         * @description Latest AI-generated narrative summary for an incident (returned by GET in a later release; used now as the structured LLM output contract).
         *
         * @example {
         *       "summary": "Checkout API latency spiked after deploy v2.4.1; error rate on payment-service rose to 12%."
         *     }
         */
        SummaryResponse: {
            /** @example Checkout API latency spiked after deploy v2.4.1; error rate on payment-service rose to 12%. */
            summary: string;
        };
        /**
         * @description Latest AI-generated severity recommendation with rationale (GET in a later release; structured LLM output contract today).
         *
         * @example {
         *       "severity": "SEV2",
         *       "reason": "Customer-facing checkout degraded for more than 15 minutes with no workaround."
         *     }
         */
        SeverityResponse: {
            severity: components["schemas"]["Severity"];
            /** @example Customer-facing checkout degraded for more than 15 minutes with no workaround. */
            reason: string;
        };
        /**
         * @description Latest AI-generated remediation suggestions (GET in a later release; structured LLM output contract today).
         *
         * @example {
         *       "solutions": [
         *         "Roll back payment-service to v2.3.9",
         *         "Scale checkout-api replicas to 6"
         *       ]
         *     }
         */
        SolutionsResponse: {
            /** @example [
             *       "Roll back payment-service to v2.3.9",
             *       "Scale checkout-api replicas to 6"
             *     ] */
            solutions: string[];
        };
        /** @description Payload for manually creating a new incident. */
        CreateIncidentRequest: {
            /** @example Checkout 5xx spike */
            title: string;
            /** @example High error rate on checkout API after deploy v2.4.1 */
            description?: string | null;
            severity: components["schemas"]["Severity"];
        };
        /** @description Partial update for an incident's mutable fields. */
        UpdateIncidentRequest: {
            status?: components["schemas"]["IncidentStatus"];
            severity?: components["schemas"]["Severity"];
        };
        /** @description An immutable comment left on an incident. */
        Comment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: uuid */
            authorId: string;
            /** @example Possible root cause is the connection pool configuration in v2.4.1 */
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Payload for adding a comment to an incident. */
        CreateCommentRequest: {
            /** @example Possible root cause is the connection pool configuration in v2.4.1 */
            content: string;
        };
        /**
         * @description Latest AI-generated postmortem draft for a resolved incident (GET in a later release; structured LLM output contract today).
         *
         * @example {
         *       "rootCause": "Connection pool misconfiguration in payment-service v2.4.1",
         *       "timeline": [
         *         "14:02 Deploy v2.4.1 completed",
         *         "14:18 Checkout error rate crossed 5%"
         *       ],
         *       "actionItems": [
         *         "Add pool-size validation to deploy checklist",
         *         "Alert on checkout latency SLO burn"
         *       ]
         *     }
         */
        PostmortemResponse: {
            /** @example Connection pool misconfiguration in payment-service v2.4.1 */
            rootCause: string;
            /** @example [
             *       "14:02 Deploy v2.4.1 completed",
             *       "14:18 Checkout error rate crossed 5%"
             *     ] */
            timeline: string[];
            /** @example [
             *       "Add pool-size validation to deploy checklist",
             *       "Alert on checkout latency SLO burn"
             *     ] */
            actionItems: string[];
        };
    };
    responses: {
        /** @description Regeneration task accepted for async processing */
        RegenAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RegenAccepted"];
            };
        };
        /** @description No incident exists with the given ID */
        IncidentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Postmortem operations require the incident to be in resolved state */
        IncidentNotResolved: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description UUID of the target incident. */
        IncidentIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    genaiHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GenAI service and Ollama reachability status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenaiHealthResponse"];
                };
            };
            /** @description Ollama unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                status?: components["schemas"]["IncidentStatus"];
                severity?: components["schemas"]["Severity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incidents in reverse-chronological order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"][];
                };
            };
        };
    };
    createIncident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentRequest"];
            };
        };
        responses: {
            /** @description Incident created; starts in open state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incident found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
            404: components["responses"]["IncidentNotFound"];
        };
    };
    updateIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIncidentRequest"];
            };
        };
        responses: {
            /** @description Updated incident */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
            404: components["responses"]["IncidentNotFound"];
        };
    };
    listIncidentEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event log entries in chronological order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentEvent"][];
                };
            };
            404: components["responses"]["IncidentNotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments in chronological order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            404: components["responses"]["IncidentNotFound"];
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            404: components["responses"]["IncidentNotFound"];
        };
    };
    regenerateSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["RegenAccepted"];
            404: components["responses"]["IncidentNotFound"];
        };
    };
    regenerateSeverity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["RegenAccepted"];
            404: components["responses"]["IncidentNotFound"];
        };
    };
    regenerateSolutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["RegenAccepted"];
            404: components["responses"]["IncidentNotFound"];
        };
    };
    regeneratePostmortem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the target incident. */
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["RegenAccepted"];
            404: components["responses"]["IncidentNotFound"];
            409: components["responses"]["IncidentNotResolved"];
        };
    };
}
