spring.application.name=incident-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/incidents}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devops}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:devops}
spring.jpa.hibernate.ddl-auto=update
nats.url=${NATS_URL:nats://localhost:4222}
