name: frontend-tests

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "services/frontend/**"
  pull_request:
    paths:
      - "services/frontend/**"
  merge_group:

jobs:
  test:
    name: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          manifest-path: services/frontend/pixi.toml
          frozen: true
          cache: true

      - name: Cache npm registry
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('services/frontend/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: pixi run --manifest-path services/frontend/pixi.toml install-ci

      - name: Run tests
        run: pixi run --manifest-path services/frontend/pixi.toml test
