name: Workflow Hygiene

on:
  pull_request:
    paths:
      - .github/workflows/**
      - .github/dependabot.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - .github/dependabot.yml

jobs:
  actionlint:
    name: Lint GitHub workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@03d0035246f3e81f36aed592ffb4bebf33a03106 # v1.7.7
